export const MASTER_CONFIGS = {
  items: {
    path: 'items',
    apiUrl: '/api/items',
    title: 'Item Master',
    columns: [
      { key: 'code', label: 'Code', width: 110 },
      { key: 'name', label: 'Item Name', width: 200 },
      { key: 'category', label: 'Category', width: 100, render: v => <span className={`badge b-${v === 'seed' ? 'stock' : v === 'gas' ? 'draft' : v === 'rough' ? 'process' : 'active'}`}>{v}</span> },
      { key: 'type', label: 'Type', width: 110, render: v => v?.replace('_', ' ') },
      { key: 'default_uom', label: 'UOM', width: 65 },
      { key: 'hsn_code', label: 'HSN', width: 90 },
      { key: 'reorder_level', label: 'Reorder', width: 75, numeric: true },
      {
        key: 'is_capital_asset', label: 'Capital?', width: 75,
        render: v => v ? <span className="badge b-active">Capital</span> : '—'
      },
      { key: 'asset_category_name', label: 'Asset Category', width: 130 },
      { key: 'status', label: 'Status', width: 85, render: v => <span className={`badge b-${v}`}>{v}</span> },
    ],
    fields: [
      { name: 'code', label: 'Item Code', required: true, placeholder: 'e.g. SEED-CVD-C' },
      { name: 'name', label: 'Item Name', required: true, wide: true, placeholder: 'Full item name' },
      { name: 'category', label: 'Category', type: 'select', options: ['seed', 'gas', 'consumable', 'rough', 'growth_run'], required: true },
      { name: 'type', label: 'Type', type: 'select', options: ['raw_material', 'finished_good'] },
      { name: 'default_uom', label: 'Default UOM', type: 'select', options: ['PCS', 'CT', 'KG', 'GM', 'CYL', 'LTR', 'HR'] },
      { name: 'hsn_code', label: 'HSN Code', placeholder: '71023100' },
      { name: 'reorder_level', label: 'Reorder Level', type: 'number' },
      { name: 'description', label: 'Description', wide: true, type: 'textarea' },
      { name: 'is_capital_asset', label: 'Capital Asset?', type: 'checkbox' },
      { name: 'fixed_asset_category_id', label: 'Asset Category', type: 'api-select', apiUrl: '/api/fixed-asset-categories?limit=500', optionLabel: 'name', optionValue: 'id' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    defaults: {
      category: 'seed', type: 'raw_material', default_uom: 'PCS', status: 'active',
      reorder_level: 0, is_capital_asset: false
    },
  },

  machines: {
    path: 'machines',
    apiUrl: '/api/machines',
    title: 'Machine Master',
    columns: [
      { key: 'code', label: 'Machine ID', width: 100 },
      { key: 'name', label: 'Machine Name' },
      { key: 'type', label: 'Type', width: 100 },
      { key: 'department_name', label: 'Department' },
      { key: 'capacity', label: 'Capacity', width: 110 },
      { key: 'last_service', label: 'Last Service', width: 100, render: v => v ? new Date(v).toLocaleDateString('en-IN') : '—' },
      { key: 'next_service', label: 'Next Service', width: 100, render: v => v ? new Date(v).toLocaleDateString('en-IN') : '—' },
      { key: 'status', label: 'Status', width: 100, render: v => <span className={`badge b-${v}`}>{v}</span> },
    ],
    fields: [
      { name: 'code', label: 'Machine ID', required: true, placeholder: 'SSD-XX' },
      { name: 'name', label: 'Machine Name', required: true, wide: true },
      { name: 'type', label: 'Type', type: 'select', options: ['CVD Reactor', 'HPHT Press', 'Laser', 'Polisher', 'QC Station'] },
      { name: 'department_id', label: 'Department', type: 'api-select', apiUrl: '/api/departments?limit=500', optionLabel: 'name', optionValue: 'id' },
      { name: 'location_id', label: 'Location', type: 'api-select', apiUrl: '/api/locations?limit=500', optionLabel: 'name', optionValue: 'id' },
      { name: 'capacity', label: 'Capacity', placeholder: '6 seeds/batch' },
      { name: 'last_service', label: 'Last Service', type: 'date' },
      { name: 'next_service', label: 'Next Service', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['running', 'maintenance', 'idle'] },
    ],
    defaults: { status: 'running' },
  },

  departments: {
    path: 'departments',
    apiUrl: '/api/departments',
    title: 'Department Master',
    columns: [
      { key: 'code', label: 'Code', width: 90 },
      { key: 'name', label: 'Department Name' },
      { key: 'head', label: 'Head' },
      { key: 'location_name', label: 'Location' },
      { key: 'staff_count', label: 'Staff', width: 60, numeric: true },
      { key: 'status', label: 'Status', width: 80, render: v => <span className={`badge b-${v}`}>{v}</span> },
    ],
    fields: [
      { name: 'code', label: 'Dept Code', required: true },
      { name: 'name', label: 'Department Name', required: true, wide: true },
      { name: 'head', label: 'Department Head' },
      { name: 'location_id', label: 'Location', type: 'api-select', apiUrl: '/api/locations?limit=500', optionLabel: 'name', optionValue: 'id' },
      { name: 'staff_count', label: 'Staff Count', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    defaults: { status: 'active', staff_count: 0 },
  },

  locations: {
    path: 'locations',
    apiUrl: '/api/locations',
    title: 'Location Master',
    columns: [
      { key: 'code', label: 'Code', width: 80 },
      { key: 'name', label: 'Location Name' },
      { key: 'type', label: 'Type', width: 80 },
      { key: 'city', label: 'City', width: 80 },
      { key: 'manager', label: 'Manager' },
      { key: 'status', label: 'Status', width: 80, render: v => <span className={`badge b-${v}`}>{v}</span> },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true },
      { name: 'name', label: 'Location Name', required: true, wide: true },
      { name: 'type', label: 'Type', type: 'select', options: ['factory', 'office', 'warehouse'] },
      { name: 'address', label: 'Address', wide: true },
      { name: 'city', label: 'City', placeholder: 'Surat' },
      { name: 'state', label: 'State', placeholder: 'Gujarat' },
      { name: 'manager', label: 'Manager' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    defaults: { type: 'factory', status: 'active', city: 'Surat', state: 'Gujarat' },
  },

  uom: {
    path: 'uom',
    apiUrl: '/api/uom',
    title: 'Units of Measure',
    columns: [
      { key: 'code', label: 'Code', width: 80 },
      { key: 'name', label: 'Unit Name' },
      { key: 'symbol', label: 'Symbol', width: 60 },
      { key: 'type', label: 'Type', width: 80 },
      { key: 'status', label: 'Status', width: 80, render: v => <span className={`badge b-${v}`}>{v}</span> },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true, placeholder: 'PCS' },
      { name: 'name', label: 'Unit Name', required: true },
      { name: 'symbol', label: 'Symbol', placeholder: 'pcs' },
      { name: 'type', label: 'Type', type: 'select', options: ['count', 'weight', 'volume', 'time'] },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    defaults: { type: 'count', status: 'active' },
  },

  'expense-categories': {
    path: 'expense-categories',
    apiUrl: '/api/expense-categories',
    title: 'Expense Categories',
    columns: [
      { key: 'code', label: 'Code', width: 90 },
      { key: 'name', label: 'Category Name' },
      { key: 'gl_account_name', label: 'GL Account' },
      { key: 'monthly_budget', label: 'Budget/Month', numeric: true, render: v => v ? `₹${Number(v).toLocaleString('en-IN')}` : '—' },
      { key: 'status', label: 'Status', width: 80, render: v => <span className={`badge b-${v}`}>{v}</span> },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true },
      { name: 'name', label: 'Category Name', required: true, wide: true },
      { name: 'gl_account_id', label: 'GL Account ID', type: 'number' },
      { name: 'monthly_budget', label: 'Monthly Budget (₹)', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    defaults: { status: 'active', monthly_budget: 0 },
  },
};
