'use strict';

/**
 * ACCOUNTING PHASE 0 — IMMEDIATE CONTAINMENT (block-only).
 *
 * One shared, pure decision module for "may this accounting record be
 * destructively removed?". No I/O, no DB, no side effects — every mutation
 * path calls the same rule instead of re-implementing its own check.
 *
 * DOCTRINE
 *   A posted / final / system-generated / payment-backed accounting record may
 *   never be HARD DELETED or silently unallocated. The user operation for such
 *   a record is a formal reversal, which is NOT part of Phase 0.
 *
 * SCOPE — this module BLOCKS ONLY. It never reverses, never recalculates a
 * bill, never mutates a balance and never repairs history.
 *
 * INTEGRITY RULE, NOT A PERMISSION
 *   These checks are properties of the RECORD, not of the actor. They are
 *   deliberately independent of role/RBAC, so a Super Admin is blocked exactly
 *   like an operator. Elevating privilege must not be able to corrupt the
 *   ledger. Callers therefore apply these guards AFTER authentication and
 *   WITHOUT any role-based bypass.
 */

/** Stable machine-readable error code returned with HTTP 409. */
const ACCOUNTING_TRANSACTION_POSTED = 'ACCOUNTING_TRANSACTION_POSTED';

/** HTTP status for a refused destructive accounting operation. */
const CONFLICT = 409;

/** Canonical operator-facing sentence, shared by every blocked path. */
const REVERSE_NOT_DELETE = 'Posted accounting transactions must be reversed, not deleted.';

/** Payment states that are final for containment purposes (never DRAFT-like). */
const FINAL_PAYMENT_STATES = Object.freeze([
  'COMPLETED', 'FULLY_APPLIED', 'PARTIAL', 'APPLIED', 'POSTED',
]);

/** Case/whitespace-insensitive compare helper. */
function norm(v) {
  return String(v == null ? '' : v).trim().toUpperCase();
}

/** Coerce a pg COUNT (which arrives as a string) to a safe non-negative integer. */
function toCount(v) {
  const n = parseInt(v, 10);
  return Number.isFinite(n) && n > 0 ? n : 0;
}

/** A journal entry is posted when its status is exactly 'posted' (any case). */
function isPostedJournal(je) {
  return !!je && norm(je.status) === 'POSTED';
}

/**
 * A JE carrying source_type was generated BY another module (payment, purchase,
 * TDS, depreciation, reversal…). Deleting it silently desynchronises that
 * module from the general ledger — the PAY-1179 defect shape.
 */
function isSystemGeneratedJournal(je) {
  return !!je && je.source_type != null && String(je.source_type).trim() !== '';
}

/**
 * Should this journal entry be protected from hard deletion?
 *
 * @param {{ je: object|null, paymentRefCount?: number|string }} ctx
 *   je              journal_entries row (id, je_number, status, source_type)
 *   paymentRefCount COUNT(*) of payments whose je_id references this JE
 * @returns {string|null} operator-facing block reason, or null when deletable
 */
function journalDeleteBlockReason({ je, paymentRefCount = 0 } = {}) {
  if (!je) return null; // absence is a 404 for the caller, not a containment block

  if (isPostedJournal(je)) {
    return `Journal entry ${je.je_number || `#${je.id}`} is POSTED. ${REVERSE_NOT_DELETE}`;
  }
  if (isSystemGeneratedJournal(je)) {
    return (
      `Journal entry ${je.je_number || `#${je.id}`} was generated by ` +
      `'${je.source_type}' and cannot be deleted directly. ${REVERSE_NOT_DELETE}`
    );
  }
  if (toCount(paymentRefCount) > 0) {
    return (
      `Journal entry ${je.je_number || `#${je.id}`} is the accounting posting for ` +
      `an existing payment. Deleting it would leave the payment, its allocations ` +
      `and the vendor ledger without a general-ledger effect. ${REVERSE_NOT_DELETE}`
    );
  }
  return null;
}

/**
 * Should an allocation belonging to this journal entry be protected?
 *
 * Deleting je_allocations for a posted/system/payment-backed JE re-opens the
 * settled bill/invoice while the GL posting stays untouched — the same
 * split-brain the JE guard prevents, reached through a different endpoint.
 *
 * @param {{ je: object|null, paymentRefCount?: number|string,
 *           jeId?: number|string|null }} ctx
 * @returns {string|null}
 */
function jeAllocationDeleteBlockReason({ je, paymentRefCount = 0, jeId = null } = {}) {
  // Fail CLOSED: an allocation whose parent JE cannot be resolved is refused.
  // An unresolvable parent is exactly the orphan state this phase contains.
  if (!je) {
    return (
      `The parent journal entry${jeId != null ? ` (#${jeId})` : ''} for this ` +
      `allocation could not be resolved. Allocation removal is refused because ` +
      `the accounting effect cannot be verified.`
    );
  }
  if (isPostedJournal(je)) {
    return (
      `Allocations of POSTED journal entry ${je.je_number || `#${je.id}`} cannot ` +
      `be removed — the settled document would re-open while the ledger posting ` +
      `remains. ${REVERSE_NOT_DELETE}`
    );
  }
  if (isSystemGeneratedJournal(je)) {
    return (
      `Allocations of system-generated journal entry ` +
      `${je.je_number || `#${je.id}`} (source '${je.source_type}') cannot be ` +
      `removed directly. ${REVERSE_NOT_DELETE}`
    );
  }
  if (toCount(paymentRefCount) > 0) {
    return (
      `Allocations of journal entry ${je.je_number || `#${je.id}`} cannot be ` +
      `removed — it is the accounting posting for an existing payment. ` +
      `${REVERSE_NOT_DELETE}`
    );
  }
  return null;
}

/**
 * Should this payment's allocations be protected from direct removal?
 *
 * Phase 0 blocks EVERY destructive touch of a final / journal-backed /
 * actively-allocated payment. This deliberately disables the existing payment
 * reversal path, which the audit proved cannot restore the general ledger (it
 * calls a journalEngine.reverseEntry that does not exist, so it writes a flag
 * and creates no compensating entry) while it DELETEs payment_allocations.
 * Re-enabling belongs to Phase 1, behind a working reversal engine.
 *
 * @param {{ payment: object|null, allocationCount?: number|string }} ctx
 * @returns {string|null}
 */
function paymentAllocationRemovalBlockReason({ payment, allocationCount = 0 } = {}) {
  if (!payment) return null; // 404 for the caller

  const status = norm(payment.status);
  const ref = payment.doc_number || `#${payment.id}`;

  // Already-neutralised payments are not re-blocked: there is nothing left to
  // destroy, and blocking them would mask a genuine already-reversed response.
  if (status === 'REVERSED' || status === 'CANCELLED') return null;

  if (FINAL_PAYMENT_STATES.includes(status)) {
    return (
      `Payment ${ref} is ${payment.status} and its allocations cannot be removed ` +
      `directly. A working reversal engine is required (Phase 1). ${REVERSE_NOT_DELETE}`
    );
  }
  if (payment.je_id != null) {
    return (
      `Payment ${ref} is backed by journal entry #${payment.je_id}. Removing its ` +
      `allocations without a compensating journal entry would desynchronise ` +
      `Accounts Payable from the general ledger. ${REVERSE_NOT_DELETE}`
    );
  }
  if (toCount(allocationCount) > 0) {
    return (
      `Payment ${ref} is actively allocated to ${toCount(allocationCount)} ` +
      `document(s). Allocation removal is refused. ${REVERSE_NOT_DELETE}`
    );
  }
  return null;
}

/** Uniform 409 body for every blocked path. */
function conflictBody(reason) {
  return { error: reason, code: ACCOUNTING_TRANSACTION_POSTED };
}

module.exports = {
  ACCOUNTING_TRANSACTION_POSTED,
  CONFLICT,
  REVERSE_NOT_DELETE,
  FINAL_PAYMENT_STATES,
  isPostedJournal,
  isSystemGeneratedJournal,
  journalDeleteBlockReason,
  jeAllocationDeleteBlockReason,
  paymentAllocationRemovalBlockReason,
  conflictBody,
};
