const { nextLotOpId } = require('./seedLotCodeService');
const { nextGrowthRunNumber } = require('./growthRunService'); // We will modify this to just yield batch numbers
const { logger } = require('../middleware/logger');

/**
 * Unified Process Engine
 * Encapsulates the entire lifecycle of a manufacturing order
 */

async function startProcess(client, opts) {
  const {
    machineId,
    processType,
    lots, // array of { source_lot_id, issued_qty }
    operatorId,
    targetRuntimeHours,
    expectedRoughQty,
    issueDate,
    expectedReturn,
    remarks,
    userId,
    departmentId
  } = opts;

  // 1. Get process rules
  const { rows: pmRows } = await client.query(
    'SELECT * FROM process_master WHERE process_code = $1 AND active = true',
    [processType]
  );
  if (!pmRows.length) throw new Error(`Unknown process type: ${processType}`);
  const processRules = pmRows[0];

  // 2. Validate machine
  const { rows: machRows } = await client.query(
    'SELECT * FROM machines WHERE id = $1 FOR UPDATE',
    [machineId]
  );
  if (!machRows.length) throw new Error(`Machine ${machineId} not found`);
  const mach = machRows[0];

  // Verify machine isn't already running something else
  if (mach.status !== 'idle' && mach.status !== 'cleaning') {
    throw new Error(`Machine is currently ${mach.status} and cannot start a new process.`);
  }

  // 3. Insert Machine Process
  const pNumRes = await client.query("SELECT nextval('manufacturing_process_seq') as n");
  const processNumber = `MP-${String(pNumRes.rows[0].n).padStart(5, '0')}`;

  // Batch Generation Logic
  // If this is a GROWTH process, we need a batch_number.
  let batchNumber = null;
  let runCycle = 1;

  if (processRules.process_group === 'GROWTH' || processType.toLowerCase() === 'growth') {
    // If the input is already a biscuit (Growth Again), we inherit the batch_number
    // We check the first lot category
    const { rows: sourceLots } = await client.query(
      'SELECT i.category, sl.lot_number, pi.batch_number, pi.run_cycle ' +
      'FROM inventory sl ' +
      'JOIN items i ON i.id = sl.item_id ' +
      'LEFT JOIN lot_process_issues pi ON pi.process_lot_id = sl.id ' + // Find if it was generated by a previous issue
      'WHERE sl.id = $1',
      [lots[0].source_lot_id]
    );

    const sourceCat = sourceLots[0]?.category;
    if (sourceCat === 'growth_run') {
       // Growth Again!
       batchNumber = sourceLots[0].lot_number.split('-R')[0]; // Strip cycle if present
       
       // Find max cycle for this batch
       const { rows: cycleRows } = await client.query(
         'SELECT MAX(run_cycle) as mx FROM machine_processes WHERE batch_number = $1',
         [batchNumber]
       );
       runCycle = (cycleRows[0].mx || 0) + 1;
    } else {
       // Fresh Seed
       batchNumber = await nextGrowthRunNumber(client, mach.code || mach.name, new Date(issueDate || Date.now()));
       runCycle = 1;
    }
  }

  const { rows: mpRows } = await client.query(
    `INSERT INTO machine_processes (
       machine_id, process_type, process_number, status, start_time,
       target_runtime_hours, expected_rough_qty, operator_id, created_by,
       batch_number, run_cycle
     ) VALUES ($1, $2, $3, 'running', NOW(), $4, $5, $6, $7, $8, $9)
     RETURNING *`,
    [
      machineId, processType, processNumber,
      targetRuntimeHours || null, expectedRoughQty || null, operatorId || null, userId,
      batchNumber, runCycle
    ]
  );
  const mp = mpRows[0];

  // 4. Update Machine Status
  await client.query(`UPDATE machines SET status = 'running' WHERE id = $1`, [machineId]);
  await client.query(
    `INSERT INTO machine_status_logs (machine_id, old_status, new_status, changed_by, remarks)
     VALUES ($1, $2, $3, $4, $5)`,
    [machineId, mach.status, 'running', userId, `Started ${processType}`]
  );

  // 5. Issue Lots
  const issueNumRes = await client.query("SELECT nextval('lot_issue_seq') as n");
  const issueDateParsed = issueDate ? new Date(issueDate) : new Date();
  const d = issueDateParsed;
  const issueNumber = `PI-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}-${String(issueNumRes.rows[0].n).padStart(4,'0')}`;

  const issues = [];
  for (const l of lots) {
    const qty = parseFloat(l.issued_qty);
    const lotOpId = await nextLotOpId(client);
    
    // Create issue
    const { rows: iRows } = await client.query(
      `INSERT INTO lot_process_issues (
         issue_number, issue_date, source_lot_id, machine_id, machine_process_id,
         issued_qty, expected_return, process_type, department_id, operator_id,
         status, created_by, remarks, batch_number
       ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'OPEN', $11, $12, $13)
       RETURNING *`,
      [
        issueNumber, issueDateParsed, l.source_lot_id, machineId, mp.id,
        qty, expectedReturn || null, processType, departmentId || null, operatorId || null,
        userId, remarks || null, batchNumber
      ]
    );
    issues.push(iRows[0]);

    // Update inventory to IN PROCESS
    await client.query(
      `UPDATE inventory 
       SET status = 'IN PROCESS', 
           location_id = $1, 
           lot_op_id = $2
       WHERE id = $3`,
      [mach.location_id, lotOpId, l.source_lot_id]
    );
  }

  return { machineProcess: mp, issues };
}

module.exports = {
  startProcess
};
