/**
 * ACCOUNTING PHASE 0 — containment regression suite.
 *
 * Two layers:
 *   1. PURE — the shared decision rule (services/accountingContainment.js).
 *   2. ROUTE — the real Express handlers driven against a FAKE database client
 *      that records every SQL string. This is what proves the critical claims:
 *      a blocked operation issues ZERO DELETE SQL, changes ZERO account
 *      balances and removes ZERO payment allocations.
 *
 * No PostgreSQL required: db/pool is stubbed through require.cache before the
 * routers are loaded. Run with:
 *     node --test tests/accountingContainment.test.js
 * (server/package.json's "test" script is `node test_db.js` and needs a live DB —
 *  do not use it for this suite.)
 */

'use strict';

const { test, after } = require('node:test');
const assert          = require('node:assert');
const Module          = require('node:module');

after(async () => {
  try {
    const poolPath = require.resolve('../db/pool');
    if (require.cache[poolPath]) {
      const p = require(poolPath);
      if (typeof p.shutdown === 'function') await p.shutdown();
      else if (p.primaryPool && typeof p.primaryPool.end === 'function') await p.primaryPool.end();
    }
  } catch (e) {}
});

const {
  ACCOUNTING_TRANSACTION_POSTED,
  CONFLICT,
  journalDeleteBlockReason,
  jeAllocationDeleteBlockReason,
  paymentAllocationRemovalBlockReason,
  conflictBody,
} = require('../services/accountingContainment');

// ── Synthetic fixtures (no production data) ──────────────────────────────────
const postedManualJe  = { id: 11, je_number: 'JE-TEST-0001', status: 'posted', source_type: null };
const draftManualJe   = { id: 12, je_number: 'JE-TEST-0002', status: 'draft',  source_type: null };
const draftPaymentJe  = { id: 13, je_number: 'JE-TEST-0003', status: 'draft',  source_type: 'payment' };
const postedPaymentJe = { id: 14, je_number: 'JE-TEST-0004', status: 'posted', source_type: 'payment' };

const completedPayment = { id: 21, doc_number: 'PAY-TEST-0001', status: 'COMPLETED', je_id: 14 };
const draftPayment     = { id: 22, doc_number: 'PAY-TEST-0002', status: 'DRAFT',     je_id: null };
const reversedPayment  = { id: 23, doc_number: 'PAY-TEST-0003', status: 'REVERSED',  je_id: 14 };

// ═════════════════════════ 1. PURE RULE ══════════════════════════════════════

test('pure: posted JE is blocked', () => {
  const r = journalDeleteBlockReason({ je: postedManualJe });
  assert.ok(r, 'posted JE must be blocked');
  assert.match(r, /POSTED/);
  assert.match(r, /reversed, not deleted/);
});

test('pure: system-generated (payment-sourced) JE is blocked even as DRAFT', () => {
  const r = journalDeleteBlockReason({ je: draftPaymentJe });
  assert.ok(r, 'system-generated JE must be blocked regardless of status');
  assert.match(r, /generated by 'payment'/);
});

test('pure: JE referenced by payments.je_id is blocked (PAY-1179 shape)', () => {
  const r = journalDeleteBlockReason({ je: draftManualJe, paymentRefCount: 1 });
  assert.ok(r, 'payment-backed JE must be blocked');
  assert.match(r, /accounting posting for an existing payment/);
});

test('pure: pg COUNT arriving as a STRING still blocks', () => {
  // node-postgres returns COUNT(*) as text unless cast; the rule must not be
  // fooled by "1" being truthy-but-not-a-number.
  const r = journalDeleteBlockReason({ je: draftManualJe, paymentRefCount: '2' });
  assert.ok(r, 'string count must be coerced and block');
});

test('pure: safe manual DRAFT with no payment reference stays deletable', () => {
  assert.equal(journalDeleteBlockReason({ je: draftManualJe, paymentRefCount: 0 }), null);
  assert.equal(journalDeleteBlockReason({ je: draftManualJe, paymentRefCount: '0' }), null);
});

test('pure: missing JE is NOT a containment block (caller returns 404)', () => {
  assert.equal(journalDeleteBlockReason({ je: null }), null);
});

test('pure: allocation of a posted parent JE is blocked', () => {
  const r = jeAllocationDeleteBlockReason({ je: postedManualJe });
  assert.ok(r);
  assert.match(r, /POSTED journal entry/);
});

test('pure: allocation of a system-generated parent JE is blocked', () => {
  const r = jeAllocationDeleteBlockReason({ je: draftPaymentJe });
  assert.ok(r);
  assert.match(r, /system-generated/);
});

test('pure: allocation of a payment-backed parent JE is blocked', () => {
  const r = jeAllocationDeleteBlockReason({ je: draftManualJe, paymentRefCount: 1 });
  assert.ok(r);
  assert.match(r, /posting for an existing payment/);
});

test('pure: allocation FAILS CLOSED when the parent JE cannot be resolved', () => {
  const r = jeAllocationDeleteBlockReason({ je: null, jeId: 999 });
  assert.ok(r, 'unresolvable parent must be refused, never silently deleted');
  assert.match(r, /could not be resolved/);
});

test('pure: allocation of a safe manual draft parent is allowed', () => {
  assert.equal(jeAllocationDeleteBlockReason({ je: draftManualJe, paymentRefCount: 0 }), null);
});

test('pure: COMPLETED payment allocation removal is blocked', () => {
  const r = paymentAllocationRemovalBlockReason({ payment: completedPayment, allocationCount: 2 });
  assert.ok(r);
  assert.match(r, /COMPLETED/);
});

test('pure: journal-backed payment is blocked even when not final-status', () => {
  const r = paymentAllocationRemovalBlockReason({
    payment: { id: 24, doc_number: 'PAY-TEST-0004', status: 'PENDING', je_id: 77 },
  });
  assert.ok(r);
  assert.match(r, /backed by journal entry #77/);
});

test('pure: actively-allocated payment is blocked with no final status and no je_id', () => {
  const r = paymentAllocationRemovalBlockReason({
    payment: { id: 25, doc_number: 'PAY-TEST-0005', status: 'PENDING', je_id: null },
    allocationCount: 3,
  });
  assert.ok(r);
  assert.match(r, /actively allocated to 3/);
});

test('pure: already REVERSED/CANCELLED payment is not re-blocked', () => {
  assert.equal(paymentAllocationRemovalBlockReason({ payment: reversedPayment }), null);
});

test('pure: unallocated DRAFT payment is not blocked', () => {
  assert.equal(
    paymentAllocationRemovalBlockReason({ payment: draftPayment, allocationCount: 0 }),
    null
  );
});

test('pure: 409 body carries the stable machine-readable code', () => {
  const body = conflictBody('why');
  assert.equal(body.code, 'ACCOUNTING_TRANSACTION_POSTED');
  assert.equal(ACCOUNTING_TRANSACTION_POSTED, 'ACCOUNTING_TRANSACTION_POSTED');
  assert.equal(CONFLICT, 409);
});

// ═════════════════════════ 2. ROUTE-LEVEL ════════════════════════════════════
// Drive the REAL handlers with a fake pool. Asserts the operation is refused
// with 409 AND that not one destructive statement reached the database.

/** Records every SQL string; answers queries from a scripted responder. */
function makeFakeClient(responder) {
  const sql = [];
  return {
    sql,
    released: false,
    async query(text, params) {
      sql.push(String(text));
      return responder(String(text), params) || { rows: [], rowCount: 0 };
    },
    release() { this.released = true; },
  };
}

function makeRes() {
  return {
    statusCode: null,
    body: null,
    status(c) { this.statusCode = c; return this; },
    json(b) { this.body = b; return this; },
  };
}

/** Install a stubbed db/pool into require.cache, then load a router fresh. */
function loadRouterWithFakePool(routerRelPath, client) {
  const poolPath   = require.resolve('../db/pool');
  const routerPath = require.resolve(routerRelPath);

  const savedPool   = require.cache[poolPath];
  const savedRouter = require.cache[routerPath];

  const fakePool = {
    query: async () => ({ rows: [], rowCount: 0 }),
    primaryPool: { connect: async () => client },
    connect: async () => client,
    transaction: async (fn) => fn(client),
  };
  const stub = new Module(poolPath, null);
  stub.filename = poolPath;
  stub.loaded   = true;
  stub.exports  = fakePool;
  require.cache[poolPath] = stub;

  delete require.cache[routerPath];
  const router = require(routerRelPath);

  // restore so other suites are unaffected
  delete require.cache[routerPath];
  if (savedPool) require.cache[poolPath] = savedPool; else delete require.cache[poolPath];
  if (savedRouter) require.cache[routerPath] = savedRouter;

  return router;
}

/** Pull a layer's terminal handler out of an Express router. */
function findHandler(router, method, routePath) {
  const layer = router.stack.find(
    l => l.route && l.route.path === routePath && l.route.methods[method]
  );
  assert.ok(layer, `route ${method.toUpperCase()} ${routePath} not found`);
  const stack = layer.route.stack;
  return stack[stack.length - 1].handle;
}

/** No statement may destroy accounting data or move a balance. */
function assertNoDestructiveSql(sql) {
  const destructive = sql.filter(s =>
    /\bDELETE\s+FROM\b/i.test(s) ||
    /\bUPDATE\s+accounts\b/i.test(s) ||
    /\bUPDATE\s+purchase_notes\b/i.test(s) ||
    /\bUPDATE\s+journal_entries\b/i.test(s) ||
    /\bUPDATE\s+payments\b/i.test(s)
  );
  assert.deepEqual(destructive, [], `blocked path issued destructive SQL:\n${destructive.join('\n')}`);
  assert.ok(sql.some(s => /^\s*ROLLBACK/i.test(s)), 'blocked path must ROLLBACK');
  assert.ok(!sql.some(s => /^\s*COMMIT/i.test(s)), 'blocked path must never COMMIT');
}

test('route: DELETE je-allocation with POSTED parent -> 409, zero DELETE SQL', async () => {
  const client = makeFakeClient((text) => {
    if (/FROM je_allocations WHERE id/i.test(text)) {
      return { rows: [{ id: 5, je_id: postedManualJe.id, target_type: 'bill', target_id: 3 }] };
    }
    if (/FROM journal_entries WHERE id/i.test(text)) return { rows: [postedManualJe] };
    if (/COUNT\(\*\)::int AS payment_refs/i.test(text)) return { rows: [{ payment_refs: 0 }] };
    return { rows: [] };
  });

  const router  = loadRouterWithFakePool('../routes/jeAllocations', client);
  const handler = findHandler(router, 'delete', '/:id');
  const res     = makeRes();

  await handler({ params: { id: '5' }, user: { id: 1, role: 'super_admin' }, body: {} }, res);

  assert.equal(res.statusCode, CONFLICT);
  assert.equal(res.body.code, ACCOUNTING_TRANSACTION_POSTED);
  assertNoDestructiveSql(client.sql);
  assert.ok(client.sql.some(s => /FROM journal_entries WHERE id = \$1 FOR UPDATE/i.test(s)),
    'parent JE must be locked with FOR UPDATE');
});

test('route: DELETE je-allocations/by-je with payment-backed parent -> 409, zero DELETE SQL', async () => {
  const client = makeFakeClient((text) => {
    if (/FROM journal_entries WHERE id/i.test(text)) return { rows: [draftManualJe] };
    if (/COUNT\(\*\)::int AS payment_refs/i.test(text)) return { rows: [{ payment_refs: 1 }] };
    return { rows: [] };
  });

  const router  = loadRouterWithFakePool('../routes/jeAllocations', client);
  const handler = findHandler(router, 'delete', '/by-je/:je_id');
  const res     = makeRes();

  await handler({ params: { je_id: String(draftManualJe.id) }, user: { id: 1, role: 'admin' }, body: {} }, res);

  assert.equal(res.statusCode, CONFLICT);
  assert.equal(res.body.code, ACCOUNTING_TRANSACTION_POSTED);
  assertNoDestructiveSql(client.sql);
});

test('route: DELETE je-allocation FAILS CLOSED when parent JE is missing', async () => {
  const client = makeFakeClient((text) => {
    if (/FROM je_allocations WHERE id/i.test(text)) {
      return { rows: [{ id: 9, je_id: 4242, target_type: 'bill', target_id: 3 }] };
    }
    if (/FROM journal_entries WHERE id/i.test(text)) return { rows: [] }; // orphan
    return { rows: [] };
  });

  const router  = loadRouterWithFakePool('../routes/jeAllocations', client);
  const handler = findHandler(router, 'delete', '/:id');
  const res     = makeRes();

  await handler({ params: { id: '9' }, user: { id: 1, role: 'admin' }, body: {} }, res);

  assert.equal(res.statusCode, CONFLICT, 'orphan parent must be refused, not deleted');
  assertNoDestructiveSql(client.sql);
});

test('route: SUPER ADMIN is blocked identically - containment is not a permission', async () => {
  for (const role of ['super_admin', 'superadmin', 'admin', 'finance', 'operator']) {
    const client = makeFakeClient((text) => {
      if (/FROM je_allocations WHERE id/i.test(text)) {
        return { rows: [{ id: 5, je_id: postedPaymentJe.id, target_type: 'bill', target_id: 3 }] };
      }
      if (/FROM journal_entries WHERE id/i.test(text)) return { rows: [postedPaymentJe] };
      if (/COUNT\(\*\)::int AS payment_refs/i.test(text)) return { rows: [{ payment_refs: 1 }] };
      return { rows: [] };
    });

    const router  = loadRouterWithFakePool('../routes/jeAllocations', client);
    const handler = findHandler(router, 'delete', '/:id');
    const res     = makeRes();

    await handler({ params: { id: '5' }, user: { id: 1, role }, body: {} }, res);

    assert.equal(res.statusCode, CONFLICT, `role ${role} must be blocked`);
    assert.equal(res.body.code, ACCOUNTING_TRANSACTION_POSTED);
    assertNoDestructiveSql(client.sql);
  }
});

test('route: direct API bypass (no UI) is refused - the handler itself enforces', async () => {
  // Simulates curl straight at the endpoint: no referer, no UI state, raw body.
  const client = makeFakeClient((text) => {
    if (/FROM je_allocations WHERE id/i.test(text)) {
      return { rows: [{ id: 7, je_id: postedManualJe.id, target_type: 'invoice', target_id: 8 }] };
    }
    if (/FROM journal_entries WHERE id/i.test(text)) return { rows: [postedManualJe] };
    if (/COUNT\(\*\)::int AS payment_refs/i.test(text)) return { rows: [{ payment_refs: 0 }] };
    return { rows: [] };
  });

  const router  = loadRouterWithFakePool('../routes/jeAllocations', client);
  const handler = findHandler(router, 'delete', '/:id');
  const res     = makeRes();

  await handler({ params: { id: '7' }, user: { id: 99, role: 'super_admin' }, body: { force: true } }, res);

  assert.equal(res.statusCode, CONFLICT);
  assertNoDestructiveSql(client.sql);
});

test('route: safe manual DRAFT allocation delete still proceeds (no over-blocking)', async () => {
  const client = makeFakeClient((text) => {
    if (/FROM je_allocations WHERE id/i.test(text)) {
      return { rows: [{ id: 6, je_id: draftManualJe.id, target_type: 'bill', target_id: 3 }] };
    }
    if (/FROM journal_entries WHERE id/i.test(text)) return { rows: [draftManualJe] };
    if (/COUNT\(\*\)::int AS payment_refs/i.test(text)) return { rows: [{ payment_refs: 0 }] };
    return { rows: [] };
  });

  const router  = loadRouterWithFakePool('../routes/jeAllocations', client);
  const handler = findHandler(router, 'delete', '/:id');
  const res     = makeRes();

  await handler({ params: { id: '6' }, user: { id: 1, role: 'admin' }, body: {} }, res);

  assert.notEqual(res.statusCode, CONFLICT, 'safe manual draft must not be blocked');
  assert.ok(client.sql.some(s => /DELETE FROM je_allocations WHERE id/i.test(s)),
    'safe path must still delete');
});
